import images from './images'

export const contacts = [
    {
        id: '1',
        userName: '\n User',
        userImg: images.user1,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Ready to play?',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: '\n User',
        userImg: images.user2,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: '\n User',
        userImg: images.user3,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: "I finished lab 17",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: '\n User',
        userImg: images.user4,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Why are you late?',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: '\n User',
        userImg: images.user5,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Today lecture is...',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: '\n User',
        userImg: images.user6,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'We need to talk..',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: '\n User',
        userImg: images.user2,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '8',
        userName: '\n User',
        userImg: images.user2,
        isOnline: false,
        lastSeen: 'Description: \n CSE major \n 2024 \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
]
