import images from './images'

export const contacts = [
    {
        id: '1',
        userName: 'Christian Gallien',
        userImg: images.user1,
        isOnline: false,
        lastSeen: '2 Days ago',
        lastMessage: 'Ready to apply?',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: 'John Lor',
        userImg: images.user2,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: 'Kristopher Tern',
        userImg: images.user3,
        isOnline: false,
        lastSeen: '3 weeks ago',
        lastMessage: "I already applied...",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: 'Ernesto Reyes',
        userImg: images.user4,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Why are you late?',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: 'Santosh Chandrasekhar',
        userImg: images.user5,
        isOnline: false,
        lastSeen: '7 hours ago',
        lastMessage: 'Today topic is...',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: 'Shrishail Baligar',
        userImg: images.user6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'We need to talk..',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: 'Michael Joseph Diaz',
        userImg: images.user6,
        isOnline: true,
        lastSeen: 'Online',
        lastMessage: 'Perfect!',
        messageInQueue: 3,
        sentDate: 'Today',
    },

 
]
