import images from './images'

export const contacts = [
    {
        id: '1',
        userName: '\nWeb Designer',
        userImg: images.user9,
        isOnline: false,
        lastSeen: 'Full time \n  \nSan Diego \n',
        lastMessage: 'Ready to play?',
        messageInQueue: 3,
        sentDate: '12/7',
    },
    {
        id: '2',
        userName: '\nSoftware Engineer',
        userImg: images.user10,
        isOnline: false,
        lastSeen: 'Part Time \n  \nLos Angeles \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '3',
        userName: '\nUI Developer',
        userImg: images.user11,
        isOnline: false,
        lastSeen: 'Part Time \n  \nMerced \n',
        lastMessage: "I finished lab 17",
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '4',
        userName: '\nBack-End Developer',
        userImg: images.user12,
        isOnline: false,
        lastSeen: 'Full time \n  \nRemote \n',
        lastMessage: 'Why are you late?',
        messageInQueue: 0,
        sentDate: 'Today',
    },
    {
        id: '5',
        userName: '\nFront-End Developer',
        userImg: images.user13,
        isOnline: false,
        lastSeen: 'Full time \n  \nFresno \n',
        lastMessage: 'Today lecture is...',
        messageInQueue: 0,
        sentDate: '23/9',
    },
    {
        id: '6',
        userName: '\nBack-End Developer',
        userImg: images.user14,
        isOnline: false,
        lastSeen: 'Part Time \n  \nRemote \n',
        lastMessage: 'We need to talk..',
        messageInQueue: 3,
        sentDate: 'Today',
    },
    {
        id: '7',
        userName: '\nUI Developer',
        userImg: images.user15,
        isOnline: false,
        lastSeen: 'Full time \n  \nSan Diego \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
    {
        id: '8',
        userName: '\nUI Developer',
        userImg: images.user16,
        isOnline: false,
        lastSeen: 'Part Time \n  \nSan Diego \n',
        lastMessage: 'Yesterday...',
        messageInQueue: 0,
        sentDate: '12/7',
    },
]
